project:
  type: website
  output-dir: docs

website:
  title: "Songzhi Liu"
  navbar:
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    grid:
      body-width: 1200px
