project:
  type: website
  output-dir: docs


website:
  title: "Sunny Hospital"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/shospital/shospital.github.io
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    grid:
      body-width: 1200px
